version: '3.8'

services:
  build:
    build:
      context: .
      dockerfile: build.Dockerfile
    image: shinchven/node:20-build
  deployment:
    build:
      context: .
      dockerfile: deployment.Dockerfile
    image: shinchven/node:20-deployment
