version: '3'

services:
  build:
    build:
      context: .
      dockerfile: build.Dockerfile
    image: shinchven/node:16-build
  deployment:
    build:
      context: .
      dockerfile: deployment.Dockerfile
    image: shinchven/node:16-deployment
