version: '3'

services:
  base:
    build:
      context: .
      dockerfile: base.Dockerfile
    image: shinchven/node:14
  build:
    build:
      context: .
      dockerfile: build.Dockerfile
    image: shinchven/node:14-build
  deployment:
    build:
      context: .
      dockerfile: deployment.Dockerfile
    image: shinchven/node:14-deployment
