name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-18:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build base image
        uses: docker/build-push-action@v3
        with:
          context: ./18
          file: ./18/base.Dockerfile
          push: false 
          tags: shinchven/node:18

      - name: Build build image
        uses: docker/build-push-action@v3
        with:
          context: ./18
          file: ./18/build.Dockerfile
          push: false 
          tags: shinchven/node:18-build

      - name: Build deployment image
        uses: docker/build-push-action@v3
        with:
          context: ./18
          file: ./18/deployment.Dockerfile
          push: false 
          tags: shinchven/node:18-deployment

  push-18:
    runs-on: ubuntu-latest
    needs: build-18 
    steps:
      - name: Change directory
        run: cd ..  # Go back to the root directory       
        
      - name: check pwd
        run: pwd
      
      - name: list all files
        run: ls -la

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push base image
        uses: docker/build-push-action@v3
        with:
          context: ./18 
          file: ./18/base.Dockerfile
          push: true
          tags: shinchven/node:18

      - name: Push build image
        uses: docker/build-push-action@v3
        with:
          context: ./18
          file: ./18/build.Dockerfile
          push: true
          tags: shinchven/node:18-build

      - name: Push deployment image
        uses: docker/build-push-action@v3
        with:
          context: ./18
          file: ./18/deployment.Dockerfile
          push: true
          tags: shinchven/node:18-deployment
