name: Build and Push Docker 16 Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build base image
        uses: docker/build-push-action@v3
        with:
          context: ./16
          file: ./16/base.Dockerfile
          push: false 
          tags: shinchven/node:16

      - name: Build build image
        uses: docker/build-push-action@v3
        with:
          context: ./16
          file: ./16/build.Dockerfile
          push: false 
          tags: shinchven/node:16-build

      - name: Build deployment image
        uses: docker/build-push-action@v3
        with:
          context: ./16
          file: ./16/deployment.Dockerfile
          push: false 
          tags: shinchven/node:16-deployment

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push base image
        uses: docker/build-push-action@v3
        with:
          context: ./16 
          file: ./16/base.Dockerfile
          push: true
          tags: shinchven/node:16

      - name: Push build image
        uses: docker/build-push-action@v3
        with:
          context: ./16
          file: ./16/build.Dockerfile
          push: true
          tags: shinchven/node:16-build

      - name: Push deployment image
        uses: docker/build-push-action@v3
        with:
          context: ./16
          file: ./16/deployment.Dockerfile
          push: true
          tags: shinchven/node:16-deployment
