name: Build and Push Node 22 Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build base image
        uses: docker/build-push-action@v5
        with:
          context: ./22
          file: ./22/base.Dockerfile
          push: false 
          tags: shinchven/node:22

      - name: Build build image
        uses: docker/build-push-action@v5
        with:
          context: ./22
          file: ./22/build.Dockerfile
          push: false 
          tags: shinchven/node:22-build
          
      - name: Build deployment image
        uses: docker/build-push-action@v5
        with:
          context: ./22
          file: ./22/deployment.Dockerfile
          push: false 
          tags: shinchven/node:22-deployment

      - name: Build deployment.ffmpeg image
        uses: docker/build-push-action@v5
        with:
          context: ./22
          file: ./22/deployment.ffmpeg.Dockerfile
          push: false 
          tags: shinchven/node:22-deployment.ffmpeg

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push base image
        uses: docker/build-push-action@v5
        with:
          context: ./22 
          file: ./22/base.Dockerfile
          push: true
          tags: shinchven/node:22

      - name: Push build image
        uses: docker/build-push-action@v5
        with:
          context: ./22
          file: ./22/build.Dockerfile
          push: true
          tags: shinchven/node:22-build

      - name: Push deployment image
        uses: docker/build-push-action@v5
        with:
          context: ./22
          file: ./22/deployment.Dockerfile
          push: true
          tags: shinchven/node:22-deployment
      
      - name: Build deployment.ffmpeg image
        uses: docker/build-push-action@v5
        with:
          context: ./22
          file: ./22/deployment.ffmpeg.Dockerfile
          push: true
          tags: shinchven/node:22-deployment.ffmpeg
