name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push-18:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          context: ./18  # Updated context path
          file: ./18/base.Dockerfile  # Updated Dockerfile path
          # push: true
          tags: shinchven/node:18

      - name: Build and push build image
        uses: docker/build-push-action@v3
        with:
          context: ./18  # Updated context path
          file: ./18/build.Dockerfile  # Updated Dockerfile path
          # push: true
          tags: shinchven/node:18-build

      - name: Build and push deployment image
        uses: docker/build-push-action@v3
        with:
          context: ./18  # Updated context path
          file: ./18/deployment.Dockerfile  # Updated Dockerfile path
          # push: true
          tags: shinchven/node:18-deployment