name: Build and Push Node 20 Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build base image
        uses: docker/build-push-action@v5
        with:
          context: ./20
          file: ./20/base.Dockerfile
          push: false 
          tags: shinchven/node:20

      - name: Build build image
        uses: docker/build-push-action@v5
        with:
          context: ./20
          file: ./20/build.Dockerfile
          push: false 
          tags: shinchven/node:20-build
          
      - name: Build deployment image
        uses: docker/build-push-action@v5
        with:
          context: ./20
          file: ./20/deployment.Dockerfile
          push: false 
          tags: shinchven/node:20-deployment

      - name: Build deployment.ffmpeg image
        uses: docker/build-push-action@v5
        with:
          context: ./20
          file: ./20/deployment.ffmpeg.Dockerfile
          push: false 
          tags: shinchven/node:20-deployment.ffmpeg

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push base image
        uses: docker/build-push-action@v5
        with:
          context: ./20 
          file: ./20/base.Dockerfile
          push: true
          tags: shinchven/node:20

      - name: Push build image
        uses: docker/build-push-action@v5
        with:
          context: ./20
          file: ./20/build.Dockerfile
          push: true
          tags: shinchven/node:20-build

      - name: Push deployment image
        uses: docker/build-push-action@v5
        with:
          context: ./20
          file: ./20/deployment.Dockerfile
          push: true
          tags: shinchven/node:20-deployment
      
      - name: Build deployment.ffmpeg image
        uses: docker/build-push-action@v5
        with:
          context: ./20
          file: ./20/deployment.ffmpeg.Dockerfile
          push: true
          tags: shinchven/node:20-deployment.ffmpeg
